# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

AWSTemplateFormatVersion: "2010-09-09"
Description: This template setups up an Amazon SageMaker notebook to use for the OpenSearch language detection demo
Parameters:
  ClientIPAddress:
    Type: String
    Description: IP address of the client who will access the OpenSearch cluster (your ip address)
    
  OpenSearchAdminUser:
    Type: String
    Default: 'aossadmin'
    Description: Admin user name for OpenSearch 
    
  OpenSearchPassword:
    NoEcho: true
    Description: The OpenSearch admin account password, please make this a strong password
    Type: String
    MinLength: 8
    MaxLength: 16
    AllowedPattern: '[a-zA-Z0-9!@#$%^&*()_+\-=\[\]{};:,.<>?]+'
    
Resources:
  # Create the s3 Bucket to store your CloudTrail logs in.
  SageMakerModelsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub '${AWS::Region}-${AWS::AccountId}-opensearch-sagemaker-demo-models'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: 'aws:kms'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      ObjectLockEnabled: false

  # Bucket policy to only allow TLS connections.
  CloudTrailBucketPolicy:
    DependsOn: 
      - SageMakerModelsBucket
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref SageMakerModelsBucket
      PolicyDocument: 
        Statement:
          - Action: 's3:*'
            Effect: Deny
            Resource: 
              - !Sub arn:${AWS::Partition}:s3:::${SageMakerModelsBucket}
              - !Sub arn:${AWS::Partition}:s3:::${SageMakerModelsBucket}/*
            Principal: '*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'

  SageMakerExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${AWS::Region}-${AWS::AccountId}-SageMaker-Execution-demo-role'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /

      # The managed policy to allow the EC2 access to SSM permissions
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerCanvasAIServicesAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerCanvasFullAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess

      # Policy to allow the EC2 to push files to the S3 bucket created. 
      Policies:
        - PolicyName: !Sub '${AWS::Region}-${AWS::AccountId}-SageMaker-Execution-demo-policy'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                  - "s3:GetObject"
                Resource: 
                  - !Sub 'arn:${AWS::Partition}:s3:::${SageMakerModelsBucket}/*'
                  - !Sub 'arn:${AWS::Partition}:s3:::${SageMakerModelsBucket}/'
              - Effect: Allow
                Action:
                  - 'es:CreateDomain'
                  - 'es:DescribeDomain'
                  - 'es:DeleteDomain'
                  - 'es:ESHttpPost'
                  - 'es:ESHttpPut'
                  - 'es:CreateElasticsearchDomain'
                  - 'es:DescribeDomainHealth'
                Resource:
                  !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*'
              - Effect: Allow
                Action:
                  - 'cloudformation:DescribeStacks'
                Resource:
                  !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/OpenSearchSageMakerDemo/*'

  SageMakerOpenSearchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${AWS::Region}-${AWS::AccountId}-SageMaker-OpenSearch-demo-role'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - opensearchservice.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: !Sub '${AWS::Region}-${AWS::AccountId}-SageMaker-OpenSearch-demo-policy'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sagemaker:InvokeEndpointAsync'
                  - 'sagemaker:InvokeEndpoint'
                Resource: 
                  - !Sub 'arn:${AWS::Partition}:sagemaker:${AWS::Region}:${AWS::AccountId}:endpoint/*'
              - Effect: Allow
                Action:
                  - 'comprehend:DetectDominantLanguage'
                Resource:
                  - '*'

  SageMakerNotebook:
    Type: AWS::SageMaker::NotebookInstance
    DependsOn: 
        - SageMakerExecutionRole
    Properties:
      NotebookInstanceName: !Sub '${AWS::Region}-${AWS::AccountId}-OpenSearch-Demo-Notebook'
      DefaultCodeRepository: 'https://github.com/jtrollin/opensearch_sagemaker_multilingual'
      InstanceType: 'ml.m5.xlarge'
      RoleArn: !GetAtt SageMakerExecutionRole.Arn
      VolumeSizeInGB: 100
      
  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    DependsOn:
      - SageMakerExecutionRole
    Properties:
      DomainName: 'ml-commons-demo-2-17'
      EngineVersion: 'OpenSearch_2.17'
      ClusterConfig:
        InstanceType: 't3.medium.search'
        InstanceCount: 1
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 100
        VolumeType: gp3
        Iops: 3500
        Throughput: 125
      IPAddressType: 'ipv4'
      EncryptionAtRestOptions:
        Enabled: true
      NodeToNodeEncryptionOptions:
        Enabled: true
      DomainEndpointOptions:
        EnforceHTTPS: true
        TLSSecurityPolicy: 'Policy-Min-TLS-1-2-2019-07'
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: !Ref OpenSearchAdminUser
          MasterUserPassword: !Ref OpenSearchPassword
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub '*'
            Action: 'es:*'
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/ml-commons-demo-2-17/*'
            Condition:
              IpAddress:
                aws:SourceIp: 
                  - !Ref ClientIPAddress
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${AWS::Region}-${AWS::AccountId}-SageMaker-Execution-demo-role'
            Action: 
              - 'es:ESHttpGet'
              - 'es:ESHttpPut'
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/ml-commons-demo-2-17/*'
            

Outputs:
  S3BucketName:
    Description: S3 Bucket Name
    Value: !Ref SageMakerModelsBucket

  SageMakerExecutionRoleArn:
    Description: SageMaker Execution Role Arn
    Value: !GetAtt SageMakerExecutionRole.Arn

  SageMakerOpenSearchRoleArn:
    Description: SageMaker OpenSearch Role Arn
    Value: !GetAtt SageMakerOpenSearchRole.Arn